using System.Globalization;
using System.Security.Cryptography;
using Microsoft.AspNetCore.WebUtilities;

namespace Sarh.Api.Nfc;

// NTAG 424 DNA SUN (Secure Unique NFC) message encode + verify.
// Reference: NXP AN12196 §11. Mirrors apps/api/src/nfc/crypto/sun-message.ts
// byte-for-byte so taps generated by either backend are interoperable.

public sealed class SunKeys
{
    public required byte[] MetaReadKey { get; init; }     // 16 bytes
    public required byte[] SdmFileReadKey { get; init; }  // 16 bytes
}

public sealed class DecodedSun
{
    public required byte[] Uid { get; init; }   // 7 bytes
    public required int Counter { get; init; }
}

public sealed class SunDecodeException : Exception
{
    public string Reason { get; }
    public SunDecodeException(string reason, string? detail = null)
        : base($"SUN decode failed: {reason}{(detail is null ? "" : $" ({detail})")}")
    {
        Reason = reason;
    }
}

public static class SunMessage
{
    private const int Block = 16;
    private const byte PiccDataTagUidAndCounter = 0xC7;
    // SV2 prefix (6 bytes): 0x3C C3 00 01 00 80
    private static readonly byte[] Sv2Prefix = { 0x3C, 0xC3, 0x00, 0x01, 0x00, 0x80 };

    public static DecodedSun Verify(SunKeys keys, string piccDataHex, string cmacHex)
    {
        var picc = ParseHex(piccDataHex, 16, "malformed_picc");
        var providedCmac = ParseHex(cmacHex, 8, "malformed_cmac");

        // 1. Decrypt PICC data with K_meta_read (AES-128-CBC, IV = 0).
        using var aes = Aes.Create();
        aes.KeySize = 128;
        aes.Mode = CipherMode.CBC;
        aes.Padding = PaddingMode.None;
        aes.Key = keys.MetaReadKey;
        aes.IV = new byte[Block];

        byte[] plaintext;
        using (var dec = aes.CreateDecryptor())
        {
            plaintext = dec.TransformFinalBlock(picc, 0, picc.Length);
        }

        if (plaintext[0] != PiccDataTagUidAndCounter)
            throw new SunDecodeException("bad_picc_tag", $"0x{plaintext[0]:x}");

        var uid = new byte[7];
        Buffer.BlockCopy(plaintext, 1, uid, 0, 7);
        int counter = plaintext[8] | (plaintext[9] << 8) | (plaintext[10] << 16);

        // 2. Derive the session CMAC key for this (uid, counter).
        var sessionKey = DeriveSessionCmacKey(keys.SdmFileReadKey, uid, counter);

        // 3. CMAC over empty input (no encrypted file data in our URL).
        var fullCmac = AesCmac.Compute(sessionKey, Array.Empty<byte>());
        var expectedShort = TakeShortCmac(fullCmac);

        if (!CryptographicOperations.FixedTimeEquals(expectedShort, providedCmac))
            throw new SunDecodeException("cmac_mismatch");

        return new DecodedSun { Uid = uid, Counter = counter };
    }

    public static (string PiccDataHex, string CmacHex) Encode(SunKeys keys, byte[] uid, int counter, byte[]? padding = null)
    {
        if (uid.Length != 7) throw new ArgumentException($"UID must be 7 bytes, got {uid.Length}", nameof(uid));
        if (counter < 0 || counter > 0xFFFFFF) throw new ArgumentException($"counter out of range: {counter}", nameof(counter));

        padding ??= RandomNumberGenerator.GetBytes(5);
        if (padding.Length != 5) throw new ArgumentException("padding must be 5 bytes", nameof(padding));

        var plaintext = new byte[Block];
        plaintext[0] = PiccDataTagUidAndCounter;
        Buffer.BlockCopy(uid, 0, plaintext, 1, 7);
        plaintext[8] = (byte)(counter & 0xff);
        plaintext[9] = (byte)((counter >> 8) & 0xff);
        plaintext[10] = (byte)((counter >> 16) & 0xff);
        Buffer.BlockCopy(padding, 0, plaintext, 11, 5);

        using var aes = Aes.Create();
        aes.KeySize = 128;
        aes.Mode = CipherMode.CBC;
        aes.Padding = PaddingMode.None;
        aes.Key = keys.MetaReadKey;
        aes.IV = new byte[Block];

        byte[] piccData;
        using (var enc = aes.CreateEncryptor())
        {
            piccData = enc.TransformFinalBlock(plaintext, 0, plaintext.Length);
        }

        var sessionKey = DeriveSessionCmacKey(keys.SdmFileReadKey, uid, counter);
        var fullCmac = AesCmac.Compute(sessionKey, Array.Empty<byte>());
        var shortCmac = TakeShortCmac(fullCmac);

        return (BytesToHexUpper(piccData), BytesToHexUpper(shortCmac));
    }

    private static byte[] DeriveSessionCmacKey(byte[] masterKey, byte[] uid, int counter)
    {
        // SV2 = SV2_PREFIX(6) || UID(7) || Counter(3 LE) = 16 bytes
        var sv2 = new byte[Block];
        Buffer.BlockCopy(Sv2Prefix, 0, sv2, 0, 6);
        Buffer.BlockCopy(uid, 0, sv2, 6, 7);
        sv2[13] = (byte)(counter & 0xff);
        sv2[14] = (byte)((counter >> 8) & 0xff);
        sv2[15] = (byte)((counter >> 16) & 0xff);
        return AesCmac.Compute(masterKey, sv2);
    }

    private static byte[] TakeShortCmac(byte[] fullCmac)
    {
        var output = new byte[8];
        for (int i = 0; i < 8; i++) output[i] = fullCmac[i * 2 + 1];
        return output;
    }

    private static byte[] ParseHex(string hex, int expectedBytes, string reason)
    {
        if (string.IsNullOrEmpty(hex) || hex.Length != expectedBytes * 2)
            throw new SunDecodeException(reason, $"expected {expectedBytes * 2} hex chars");
        try
        {
            return Convert.FromHexString(hex);
        }
        catch (FormatException)
        {
            throw new SunDecodeException(reason, "non-hex characters");
        }
    }

    private static string BytesToHexUpper(byte[] bytes) => Convert.ToHexString(bytes);

    public sealed class ParsedUrl
    {
        public required string PiccDataHex { get; init; }
        public required string CmacHex { get; init; }
        public string? UidHex { get; init; }
    }

    public static ParsedUrl ParseUrl(string input)
    {
        int q = input.IndexOf('?');
        var qs = q == -1 ? input : input[(q + 1)..];
        var parsed = QueryHelpers.ParseQuery(qs);
        var picc = TryGet(parsed, "p") ?? TryGet(parsed, "picc_data") ?? "";
        var cmac = TryGet(parsed, "c") ?? TryGet(parsed, "cmac") ?? "";
        if (string.IsNullOrEmpty(picc) || string.IsNullOrEmpty(cmac))
            throw new SunDecodeException("malformed_picc", "missing p / c query parameters");

        var uid = TryGet(parsed, "u") ?? TryGet(parsed, "uid");
        if (uid is not null && !IsValidUidHex(uid))
        {
            // Drop malformed hint silently.
            return new ParsedUrl { PiccDataHex = picc, CmacHex = cmac };
        }
        return new ParsedUrl { PiccDataHex = picc, CmacHex = cmac, UidHex = uid };
    }

    private static string? TryGet(Dictionary<string, Microsoft.Extensions.Primitives.StringValues> q, string key)
        => q.TryGetValue(key, out var v) ? v.ToString() : null;

    private static bool IsValidUidHex(string s)
    {
        if (s.Length != 14) return false;
        foreach (var ch in s)
        {
            bool ok = (ch >= '0' && ch <= '9') || (ch >= 'a' && ch <= 'f') || (ch >= 'A' && ch <= 'F');
            if (!ok) return false;
        }
        return true;
    }
}
